# Generated by Django 6.0.1 on 2026-01-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(max_length=50)),
                ('sentiment', models.FloatField()),
                ('song_title', models.CharField(max_length=200)),
                ('song_artist', models.CharField(blank=True, max_length=200)),
                ('song_url', models.URLField(blank=True)),
            ],
        ),
    ]
