# Generated by Django 6.0.1 on 2026-01-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='song_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
