# Generated by Django 6.0.1 on 2026-01-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0002_post_bg_color_post_emotion_alter_post_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comfort_message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
